// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJSQI79SWzLH0ICamvu4tAE4gMxNXCIW0',
    appId: '1:318058925617:web:f978ae6b8f8caee150cf10',
    messagingSenderId: '318058925617',
    projectId: 'let-s-buy-dee22',
    authDomain: 'let-s-buy-dee22.firebaseapp.com',
    storageBucket: 'let-s-buy-dee22.appspot.com',
    measurementId: 'G-RLVPPYG57M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4StwRPyGMWBR2uCGoi2WMjoSNaPnR_6Q',
    appId: '1:318058925617:android:14fdb5fa0a9ebe8d50cf10',
    messagingSenderId: '318058925617',
    projectId: 'let-s-buy-dee22',
    storageBucket: 'let-s-buy-dee22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Yv24xidbhLqsD6A762NWsmNtN_8X-TM',
    appId: '1:318058925617:ios:61a5db7e94bdbb7d50cf10',
    messagingSenderId: '318058925617',
    projectId: 'let-s-buy-dee22',
    storageBucket: 'let-s-buy-dee22.appspot.com',
    androidClientId: '318058925617-ahm25b89v0c2msii4dnafd9kvjgkm5mg.apps.googleusercontent.com',
    iosClientId: '318058925617-8uo1v2v5rss5obf85e5oeu4lvbru9mkq.apps.googleusercontent.com',
    iosBundleId: 'com.siajdynamicinnovations.siajEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Yv24xidbhLqsD6A762NWsmNtN_8X-TM',
    appId: '1:318058925617:ios:61a5db7e94bdbb7d50cf10',
    messagingSenderId: '318058925617',
    projectId: 'let-s-buy-dee22',
    storageBucket: 'let-s-buy-dee22.appspot.com',
    androidClientId: '318058925617-ahm25b89v0c2msii4dnafd9kvjgkm5mg.apps.googleusercontent.com',
    iosClientId: '318058925617-8uo1v2v5rss5obf85e5oeu4lvbru9mkq.apps.googleusercontent.com',
    iosBundleId: 'com.siajdynamicinnovations.siajEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJSQI79SWzLH0ICamvu4tAE4gMxNXCIW0',
    appId: '1:318058925617:web:398e80117e02876c50cf10',
    messagingSenderId: '318058925617',
    projectId: 'let-s-buy-dee22',
    authDomain: 'let-s-buy-dee22.firebaseapp.com',
    storageBucket: 'let-s-buy-dee22.appspot.com',
    measurementId: 'G-X7BEP7CTJL',
  );

}